version: '3.9'

services:
  database:
    container_name: app_mysql_dev
    image: mariadb:10.4
    env_file: .env
    environment:
      TZ: Asia/Seoul
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
